# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lenovo/Desktop/b/b.cache/wt [current_project]
set_property parent.project_path C:/Users/lenovo/Desktop/b/b.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/divide.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/dual2bcd.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/bcd2ascii.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/clk_blink.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/threshold.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/trip_time.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/trip_distance.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/max.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/inst_speed.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/clk_1s.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/gen_10ms.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/average_speed.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/gen_1s.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/disp_out.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/calcul_block.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/control_block.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/imports/sources/top_of_your_bicycle.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/imports/sources/syn/pulse_shape.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/imports/sources/syn/kmh_test.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/CLK_DIVIDER_BIKE.v
  C:/Users/lenovo/Desktop/b/b.srcs/sources_1/imports/sources/syn/global_toplevel.v
}
read_vhdl -library xil_defaultlib C:/Users/lenovo/Desktop/b/b.srcs/sources_1/imports/sources/syn/LCD_Controller.vhd
read_xdc C:/Users/lenovo/Desktop/b/b.srcs/constrs_1/imports/syn/stop_watch.xdc
set_property used_in_implementation false [get_files C:/Users/lenovo/Desktop/b/b.srcs/constrs_1/imports/syn/stop_watch.xdc]

read_xdc C:/Users/lenovo/Desktop/b/b.srcs/constrs_1/imports/syn/timings.xdc
set_property used_in_implementation false [get_files C:/Users/lenovo/Desktop/b/b.srcs/constrs_1/imports/syn/timings.xdc]

synth_design -top global_toplevel -part xc7z010clg400-1
write_checkpoint -noxdef global_toplevel.dcp
catch { report_utilization -file global_toplevel_utilization_synth.rpt -pb global_toplevel_utilization_synth.pb }
