# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-11672-lenovo1/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z010clg400-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/divide.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/dual2bcd.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/bcd2ascii.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/clk_blink.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/threshold.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/trip_time.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/trip_distance.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/max.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/inst_speed.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/clk_1s.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/gen_10ms.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/average_speed.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/gen_1s.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/disp_out.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/calcul_block.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/control_block.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/imports/sources/top_of_your_bicycle.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/imports/sources/syn/pulse_shape.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/imports/sources/syn/kmh_test.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/new/CLK_DIVIDER_BIKE.v
      C:/Users/lenovo/Desktop/b/b.srcs/sources_1/imports/sources/syn/global_toplevel.v
    }
      rt::read_vhdl -lib xil_defaultlib C:/Users/lenovo/Desktop/b/b.srcs/sources_1/imports/sources/syn/LCD_Controller.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top global_toplevel
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-11672-lenovo1/"
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
